### ISSUE TITLE
Error in plotHierachicalStructure

### ISSUE THREAD

**Issue by ZihaoChen490** [ZhenyiWangTHU/MarkovHC#1]
Hi Dr Wang,
   It's good to use MarkovHC. However, I get "Error in layout_fun(graph, circular = circular, ...) :   Parameter is useless (node.positions = nodesPosition)"  when I apply the function called "plotHierarchicalStructure" after checking num of colorVectors and Levels carefully.  If there is anything else that I miss?
Sincerely,
Zihao

**Comment by ZhenyiWangTHU** [comment]
It seems that it is caused by the different version of 'ggraph' package. And 'MarkovHC' needs v.1.0.2. 'ggraph'. If you have any further questions, feel free to contact me.

**Comment by ZihaoChen490** [comment]
Thanks a lot. Changing the version of 'ggraph' package solved my problem.

**Comment by ZhenyiWangTHU** [comment]
Good to hear that.
